import { memo } from "react";

const HomePage = memo(() => {
    return(
        <div >
            <h1>Home Page</h1>
            <p>
                Nunc mollis imperdiet neque vitae molestie. Maecenas accumsan dui nec ornare elementum. Etiam vestibulum auctor est nec maximus. Sed ornare eros id fringilla dignissim. Donec elementum nisl felis, eget luctus felis tempor ut. Donec pretium sit amet risus sit amet hendrerit. Donec nisi felis, porta vel orci eget, luctus porttitor risus. Nunc et purus eu lectus elementum semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris pretium sapien risus, sed rhoncus mauris gravida quis. Praesent varius non est convallis faucibus. Aliquam suscipit diam quis lectus ultricies congue.

Duis laoreet arcu non ante lacinia gravida. Vivamus lobortis nulla purus. Quisque scelerisque elementum lorem, ac aliquam ex gravida ac. Mauris in eros venenatis, sollicitudin diam a, suscipit nunc. Maecenas rutrum, risus non laoreet gravida, mi metus fermentum erat, euismod volutpat magna diam nec turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet mauris eu augue convallis, eget consequat nulla vehicula. Cras at est ac dolor sagittis eleifend in eu turpis. Vivamus porttitor est sed mauris sagittis, sit amet molestie justo rutrum. Cras congue at quam a mollis. Morbi consectetur tincidunt magna et aliquet. Nunc posuere lorem ut magna cursus, a cursus augue ultricies. Maecenas sed ex at ex lacinia luctus. Nunc bibendum sapien in risus finibus, in congue lectus commodo. Ut in massa id justo maximus viverra ut non nisl. Etiam ac ex at eros pretium suscipit et quis magna.

Aliquam mattis ullamcorper metus ac porttitor. Vestibulum non tortor risus. Praesent vitae justo sed eros sagittis gravida. Sed ultrices porttitor mauris vel sodales. Sed lobortis magna in molestie tempus. Nunc interdum accumsan orci, mattis porta eros. Aenean sed mauris vel nunc consequat ullamcorper eget eget tellus. Aenean scelerisque turpis vel nibh maximus, in fringilla sapien scelerisque. Phasellus ullamcorper aliquet orci, quis faucibus ipsum pretium a. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis vel nunc diam. Maecenas tempus nisl ac leo lacinia vulputate.
            </p>
            <p>
                Nunc mollis imperdiet neque vitae molestie. Maecenas accumsan dui nec ornare elementum. Etiam vestibulum auctor est nec maximus. Sed ornare eros id fringilla dignissim. Donec elementum nisl felis, eget luctus felis tempor ut. Donec pretium sit amet risus sit amet hendrerit. Donec nisi felis, porta vel orci eget, luctus porttitor risus. Nunc et purus eu lectus elementum semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris pretium sapien risus, sed rhoncus mauris gravida quis. Praesent varius non est convallis faucibus. Aliquam suscipit diam quis lectus ultricies congue. Duis laoreet arcu non ante lacinia gravida. Vivamus lobortis nulla purus. Quisque scelerisque elementum lorem, ac aliquam ex gravida ac. Mauris in eros venenatis, sollicitudin diam a, suscipit nunc. Maecenas rutrum, risus non laoreet gravida, mi metus fermentum erat, euismod volutpat magna diam nec turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet mauris eu augue convallis, eget consequat nulla vehicula. Cras at est ac dolor sagittis eleifend in eu turpis. Vivamus porttitor est sed mauris sagittis, sit amet molestie justo rutrum. Cras congue at quam a mollis. Morbi consectetur tincidunt magna et aliquet. Nunc posuere lorem ut magna cursus, a cursus augue ultricies. Maecenas sed ex at ex lacinia luctus. Nunc bibendum sapien in risus finibus, in congue lectus commodo. Ut in massa id justo maximus viverra ut non nisl. Etiam ac ex at eros pretium suscipit et quis magna. Aliquam mattis ullamcorper metus ac porttitor. Vestibulum non tortor risus. Praesent vitae justo sed eros sagittis gravida. Sed ultrices porttitor mauris vel sodales. Sed lobortis magna in molestie tempus. Nunc interdum accumsan orci, mattis porta eros. Aenean sed mauris vel nunc consequat ullamcorper eget eget tellus. Aenean scelerisque turpis vel nibh maximus, in fringilla sapien scelerisque. Phasellus ullamcorper aliquet orci, quis faucibus ipsum pretium a. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis vel nunc diam. Maecenas tempus nisl ac leo lacinia vulputate.
            </p>
        </div>
    )
});

export default HomePage;